include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.graphql.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
  errors:
    invalid_annotation_target: ignore

######################################################
# Dart Code Metric
######################################################

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-methods: 10
    number-of-parameters: 4
    source-lines-of-code: 50
    weight-of-class: 0.33
  rules:
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    # - avoid-ignoring-return-values
    # - avoid-late-keyword
    - avoid-collection-methods-with-unrelated-types
    - avoid-global-state
    # - avoid-dynamic
    # - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-non-null-assertion
    # - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - avoid-unrelated-type-assertions
    # - avoid-border-all
    - avoid-non-null-assertion
    # - avoid-non-ascii-symbols
    # - ban-name
    - binary-expression-operand-order
    - double-literal-format
    # - format-comment
    # - member-ordering-extended
    # - member-ordering
    # - newline-before-return
    - no-boolean-literal-compare
    # - no-empty-block
    # - no-equal-arguments
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration
    - prefer-conditional-expressions
    # - prefer-commenting-analyzer-ignores
    # - prefer-correct-identifier-length
    - prefer-correct-type-name
    # - prefer-extracting-callbacks
    - prefer-first
    - prefer-last
    - prefer-async-await
    - prefer-match-file-name
    - prefer-trailing-comma
    - prefer-immediate-return
    - prefer-moving-to-variable
    - tag-name
    - prefer-single-widget-per-file:
        ignore-private-widgets: true

######################################################
# flutter_lints
######################################################

linter:
  rules:
    use_key_in_widget_constructors: false
    always_use_package_imports: false
    avoid_dynamic_calls: false
    avoid_print: true
    avoid_relative_lib_imports: false
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: false
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: false
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    diagnostic_describe_all_properties: false
    empty_statements: false
    hash_and_equals: true
    iterable_contains_unrelated_type: false
    list_remove_unrelated_type: trye
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    no_leading_underscores_for_local_identifiers: true
    prefer_relative_imports: true
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    unsafe_html: true
    use_build_context_synchronously: true
    valid_regexps: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: false
    always_require_non_null_named_parameters: true
    always_specify_types: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: false
    avoid_as: false
    avoid_bool_literals_in_conditional_expressions: false
    avoid_catches_without_on_clauses: false
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: false
    avoid_double_and_int_checks: false
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: false
    avoid_implementing_value_types: true
    avoid_init_to_null: true
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_on_closure_parameters: false
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cascade_invocations: false
    cast_nullable_to_non_nullable: true
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: true
    deprecated_consistency: true
    depend_on_referenced_packages: false
    directives_ordering: true
    do_not_use_environment: true
    empty_catches: true
    empty_constructor_bodies: true
    eol_at_end_of_file: false
    exhaustive_cases: true
    file_names: true
    flutter_style_todos: false
    implementation_imports: false
    join_return_with_assignment: true
    library_names: true
    library_prefixes: true
    library_private_types_in_public_api: false
    lines_longer_than_80_chars: false
    missing_whitespace_between_adjacent_strings: true
    no_default_cases: false
    no_runtimeType_toString: true
    no_leading_underscores_for_library_prefixes: true
    non_constant_identifier_names: true
    noop_primitive_operations: true
    null_check_on_nullable_type_parameter: true
    null_closures: true
    omit_local_variable_types: false
    one_member_abstracts: false
    only_throw_errors: true
    overridden_fields: true
    package_api_docs: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: false
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_double_quotes: false
    prefer_equal_for_default_values: true
    prefer_expression_function_bodies: false
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_parameters: false
    prefer_for_elements_to_map_fromIterable: true
    prefer_foreach: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: false
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_int_literals: false
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: false
    public_member_api_docs: false
    recursive_getters: true
    require_trailing_commas: false
    sized_box_for_whitespace: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: false
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_final: false
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_late: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: false
    use_string_buffers: true
    use_test_throws_matchers: true
    void_checks: true
    xzavoid_equals_and_hash_code_on_mutable_classes: true
