name: navigation
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^6.2.0

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain

dev_dependencies:
  flutter_lints: 2.0.1
  dart_code_metrics: ^5.7.2
  auto_route_generator: ^6.2.0
  build_runner: 2.1.11